export default {
  landing: {
    heading: 'Rent any car any time',
    login: {
      heading: 'Login to your account',
      help: 'You can view your rental history',
      email: 'Email',
      password: 'Password',
      cta: 'Login',
      goToSignup: 'Need an account? Signup',
    },
    signup: {
      heading: 'Create an account',
      help: 'You will be able to view and rent a car in under 5 minutes',
      name: 'Name',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      phoneNumber: 'Phone Number',
      cta: 'Sign up',
      goToLogin: 'Have an account? Login',
    },
  },
  listings: {
    header: 'Car listings',
    subheading: 'Test',
    empty: 'No cars are available',
    create: 'Add new car',
    car: {
      name: 'Name',
      color: 'Color:',
      rent: 'Rent',
      price: 'Price:',
    },
  },
  header: {
    listings: 'Listings',
    history: 'History',
    logout: 'Logout',
    name: 'Name',
    admin: 'Admin',
  },
  upsertCar: {
    insertHeading: 'Add a new car',
    updatedHeading: 'Update car details',
    helpText: 'More details information will help users to find their needs faster',
    images: 'Upload images',
    upload: 'Upload...',
    name: 'Name',
    desc: 'Description',
    price: 'Price per hour',
    color: 'Color',
    submit: 'Save changes',
    cancel: 'Cancel',
  },
  deleteCar: {
    title: 'Are you sure to delete this car?',
    confirm: 'Delete',
  },
  rent: {
    back: 'Back to listings',
    rent: 'Reserve this car',
    helpText: 'Total will be calculated depending on reservation hours',
    startDate: 'From',
    endDate: 'To',
    time: 'At',
    confirm: 'Rent',
  },
  hideDialog: 'Close',
};
